# Generated by Django 6.0 on 2025-12-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='Уникальный номер или название комнаты', max_length=50, unique=True, verbose_name='Номер комнаты')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Стоимость проживания за одну ночь', max_digits=10, verbose_name='Цена за ночь')),
                ('capacity', models.PositiveIntegerField(help_text='Количество мест в комнате', verbose_name='Вместимость')),
                ('description', models.TextField(blank=True, help_text='Подробное описание комнаты и удобств', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли комната для бронирования', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'db_table': 'rooms',
                'ordering': ['room_number'],
                'indexes': [models.Index(fields=['price_per_night'], name='room_price_idx'), models.Index(fields=['capacity'], name='room_capacity_idx'), models.Index(fields=['is_active'], name='room_active_idx')],
            },
        ),
    ]
