# Generated by Django 6.0 on 2025-12-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='room_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_capacity_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='room_active_idx',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Фотография комнаты', null=True, upload_to='rooms/', verbose_name='Изображение'),
        ),
    ]
