# Generated by Django 6.0 on 2025-12-27 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_remove_room_room_price_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(help_text='Дата начала бронирования', verbose_name='Дата заезда')),
                ('check_out', models.DateField(help_text='Дата окончания бронирования', verbose_name='Дата выезда')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Автоматически рассчитывается при создании', max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено')], db_index=True, default='active', max_length=20, verbose_name='Статус бронирования')),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Время отмены бронирования', null=True, verbose_name='Дата отмены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cancelled_by', models.ForeignKey(blank=True, help_text='Пользователь или администратор, отменивший бронирование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил')),
                ('room', models.ForeignKey(help_text='Забронированная комната', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Комната')),
                ('user', models.ForeignKey(help_text='Пользователь, создавший бронирование', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
